call plug#begin('~/.vim/plugged')

Plug 'junegunn/vim-easy-align'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'fatih/vim-go'
Plug 'vim-airline/vim-airline'
Plug 'scrooloose/nerdtree'
Plug 'xoria256.vim'
Plug 'rust-lang/rust.vim'
Plug 'Valloric/YouCompleteMe'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'mileszs/ack.vim'

call plug#end()

filetype plugin indent on

set background=dark
set relativenumber

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

set hlsearch

" git grep command
nnoremap <C-F> :Ggr <cword><CR>
command -nargs=+ Ggr execute 'silent Ggrep!' <q-args> | cw | redraw!


" search work under the cursor using 
let g:ackprg = 'ag --vimgrep'
nmap <C-k>    mo:Ack! "\b<cword>\b" <CR>

set visualbell

silent! colorscheme xoria256
