#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# set editor
export EDITOR=vim
export VISUAL=$EDITOR

# add golang to the path
export PATH=$PATH:~/tools/go/bin
export PATH=$PATH:~/go/bin

# add .local/bin to path
export PATH=$PATH:~/.local/bin
